language: scala

jdk:
  - openjdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache/
  - $HOME/.sbt/boot/

script: "sbt +clean +coverage +test && sbt coverageAggregate"

after_success: "sbt coveralls"
